apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tasklist-api
  namespace: argocd
spec:
  ignoreDifferences:
  - group: networking.k8s.io
    kind: Ingress
    jsonPointers:
    - /status
  project: default

  source:
    repoURL: https://github.com/TaskWorks-Solutions/TaskListAPI.git
    targetRevision: main
    path: k8s/base

  destination:
    server: https://kubernetes.default.svc
    namespace: tasklist

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
