apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tasklist-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: tasklist.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tasklist-backend
                port:
                  number: 8080
